-- MySQL Workbench Synchronization
-- Generated: 2016-06-23 22:42
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Dimon

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `PERSONS_DB` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `PERSONS_DB`.`USERS` (
  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(20) NOT NULL,
  `PASSWORD` VARCHAR(20) NOT NULL,
  `IS_ACTIVE` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_NAME_UNIQUE` (`USER_NAME` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `PERSONS_DB`.`ROLES` (
  `ROLE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ROLE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `PERSONS_DB`.`USERS_ROLES` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(11) NOT NULL,
  `ROLE_ID` INT(11) NOT NULL,
  INDEX `fk_USERS_ROLES_USERS_idx` (`USER_ID` ASC),
  INDEX `fk_USERS_ROLES_ROLES1_idx` (`ROLE_ID` ASC),
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_USERS_ROLES_USERS`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `PERSONS_DB`.`USERS` (`USER_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_ROLES_ROLES1`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `PERSONS_DB`.`ROLES` (`ROLE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
