-- MySQL Workbench Synchronization
-- Generated: 2016-09-19 17:45
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Dimon

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `restoran` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `restoran`.`USER` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `NAME` VARCHAR(20) NOT NULL COMMENT '',
  `SURNAME` VARCHAR(20) NOT NULL COMMENT '',
  `PHONE` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `POSITION` VARCHAR(20) NULL DEFAULT NULL COMMENT '',
  `SLARY` REAL NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
